name: dbt_capstone
version: '1.0.0'
config-version: 2

profile: dbt_capstone

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  dbt_capstone:
    staging:
      +materialized: view
    marts:
      +materialized: incremental