name: 'dbt_capstone'
version: '1.0.0'
config-version: 2

# This must match the name in your profiles.yml
profile: 'dbt_capstone'

# Where DBT looks for models
model-paths: ["models"]

# Optional folder for seeds (CSV data you want to upload to BigQuery)
seed-paths: ["seeds"]

# Default settings for all models in the project
models:
  dbt_capstone:
    staging:
      +materialized: view
    marts:
      +materialized: table